import math as m
number = float(input("enter float value"))
print("original value",number)
print(f"ceil value of {number} ",m.ceil(number)) 
print(f"floor value of {number} ",m.floor(number)) 
print(f" truncated value {number} ",m.trunc(number)) 
print(f" float and integer part of {number}")
print(m.modf(number))

number2 = int(input("any positive/negative number"))
print(f"Original negative number {number2} and now in positive ",m.copysign(number2,1))
print(f"Original negative number {number2} and now in negative ",m.copysign(number2,-1))
print(f" absolute value of {number2} ",m.fabs(number2))
number2 = int(m.fabs(number2))
print(f"factorial of {number2} ",m.factorial(number2))
print(f"reminder of 10 %3 ",m.fmod(10,3))